import {
  mdiPower,
  mdiLightbulb,
  mdiLightbulbOutline,
  mdiSnowflake,
  mdiAirConditioner,
  mdiWater,
  mdiWaterPercent,
  mdiRadiator,
  mdiFire,
  mdiRobotVacuum,
  mdiPlay,
  mdiPause,
  mdiHome,
  mdiHomeAccount,
  mdiKeyVariant,
  mdiKeyAlert,
  mdiCellphone,
  mdiWifi,
  mdiFingerprint,
  mdiHistory,
  mdiTag,
  mdiSignalDistanceVariant,
  mdiClose,
  mdiCheck,
  mdiChevronUp,
  mdiChevronDown,
  mdiLeaf,
  mdiFan,
  mdiFanAuto,
  mdiFanSpeed1,
  mdiFanSpeed2,
  mdiFanSpeed3,
  mdiAutorenew,
  mdiWeatherWindy,
  mdiWeatherTornado,
  mdiSpeedometerSlow,
  mdiSpeedometerMedium,
  mdiSpeedometer,
  mdiVolumeHigh,
  mdiMicrosoftWindows,
  mdiGamepadVariant,
  mdiSleep,
  mdiRestart,
  mdiWeatherSunny,
  mdiWeatherPartlyCloudy,
  mdiWeatherNightPartlyCloudy,
  mdiWeatherNight,
  mdiWeatherCloudy,
  mdiWeatherRainy,
  mdiWeatherHail,
  mdiWeatherFog,
  mdiWeatherLightningRainy,
  mdiWeatherSnowy,
  mdiWeatherSunsetDown,
  mdiWeatherSunsetUp,
  mdiAlarm,
  mdiAccountOff,
  mdiExitRun,
  mdiViewDashboard,
  mdiRobot,
  mdiPaletteOutline,
  mdiCog,
  mdiMicrophone,
  mdiWhiteBalanceSunny,
  mdiPlus,
  mdiMinus,
  mdiShieldCheck,
  mdiAlertCircle,
  mdiLoading,
  mdiLightningBolt,
  mdiBrightness6,
  mdiBatteryCharging,
  mdiBattery,
  mdiPlayCircle,
  mdiRocketLaunch,
  mdiBellRing,
  mdiEye,
  mdiEyeOff,
  mdiSend,
  mdiWaveform
} from '@mdi/js'

export const iconMap: Record<string, string> = {
  // Common / Navigation
  dashboard: mdiViewDashboard,
  grid_view: mdiViewDashboard,
  automations: mdiRobot,
  smart_toy: mdiRobot,
  scenes: mdiPaletteOutline,
  palette: mdiPaletteOutline,
  settings: mdiCog,
  mic: mdiMicrophone,
  close: mdiClose,
  check: mdiCheck,
  expand_less: mdiChevronUp,
  expand_more: mdiChevronDown,
  add: mdiPlus,
  remove: mdiMinus,

  // Power (Home Assistant standard IEEE 5021 symbol)
  power: mdiPower,
  power_settings_new: mdiPower,

  // Light
  lightbulb: mdiLightbulb,
  lightbulb_outline: mdiLightbulbOutline,
  light_mode: mdiWhiteBalanceSunny,
  nightlight: mdiWeatherNight,
  brightness_medium: mdiBrightness6,

  // AC & Climate
  mode_cool: mdiSnowflake,
  ac_unit: mdiSnowflake,
  air_conditioner: mdiAirConditioner,
  water_drop: mdiWater,
  water_percent: mdiWaterPercent,
  mode_heat: mdiRadiator,
  radiator: mdiRadiator,
  fire: mdiFire,
  eco: mdiLeaf,
  bolt: mdiLightningBolt,
  mode_fan: mdiFan,
  fan: mdiFan,
  fan_auto: mdiFanAuto,
  fan_speed_1: mdiFanSpeed1,
  fan_speed_2: mdiFanSpeed2,
  fan_speed_3: mdiFanSpeed3,
  'fan-auto': mdiFanAuto,
  'fan-speed-1': mdiFanSpeed1,
  'fan-speed-2': mdiFanSpeed2,
  'fan-speed-3': mdiFanSpeed3,
  fan1: mdiFanSpeed1,
  fan2: mdiFanSpeed2,
  fan3: mdiFanSpeed3,
  autorenew: mdiAutorenew,
  air: mdiWeatherWindy,
  cyclone: mdiWeatherTornado,

  // Robot Vacuum
  vacuum: mdiRobotVacuum,
  robot_vacuum: mdiRobotVacuum,
  cleaner: mdiRobotVacuum,
  play: mdiPlay,
  play_arrow: mdiPlay,
  play_circle: mdiPlayCircle,
  pause: mdiPause,
  home: mdiHome,
  volume_up: mdiVolumeHigh,
  notifications_active: mdiBellRing,
  bell_ring: mdiBellRing,
  battery_charging_full: mdiBatteryCharging,
  battery_full: mdiBattery,
  speed_standard: mdiSpeedometerSlow,
  speed_boost: mdiSpeedometerMedium,
  speed_max: mdiSpeedometer,
  rocket_launch: mdiRocketLaunch,

  // PC & Devices
  desktop_windows: mdiMicrosoftWindows,
  windows: mdiMicrosoftWindows,
  sports_esports: mdiGamepadVariant,
  controller: mdiGamepadVariant,
  bedtime: mdiSleep,
  sleep: mdiSleep,
  restart_alt: mdiRestart,
  restart: mdiRestart,

  // Sensors & Location
  home_pin: mdiHomeAccount,
  home_account: mdiHomeAccount,
  smartphone: mdiCellphone,
  wifi: mdiWifi,
  fingerprint: mdiFingerprint,
  history: mdiHistory,
  key: mdiKeyVariant,
  vpn_key_alert: mdiKeyAlert,
  key_alert: mdiKeyAlert,
  sell: mdiTag,
  tag: mdiTag,
  network_ping: mdiSignalDistanceVariant,

  // Weather
  wb_sunny: mdiWeatherSunny,
  sunny: mdiWeatherSunny,
  partly_cloudy_day: mdiWeatherPartlyCloudy,
  partly_cloudy_night: mdiWeatherNightPartlyCloudy,
  clear_night: mdiWeatherNight,
  cloud: mdiWeatherCloudy,
  rainy: mdiWeatherRainy,
  grain: mdiWeatherHail,
  foggy: mdiWeatherFog,
  thunderstorm: mdiWeatherLightningRainy,
  weather_snowy: mdiWeatherSnowy,
  humidity_mid: mdiWaterPercent,
  wb_twilight: mdiWeatherSunsetDown,
  sunrise: mdiWeatherSunsetUp,

  // Automations & Scenes
  alarm: mdiAlarm,
  person_off: mdiAccountOff,
  logout: mdiExitRun,

  // Status & Auth
  auto_awesome: mdiShieldCheck,
  error: mdiAlertCircle,
  progress_activity: mdiLoading,
  visibility: mdiEye,
  visibility_off: mdiEyeOff,
  send: mdiSend,
  graphic_eq: mdiWaveform
}

export function getIconPath(nameOrPath?: string): string {
  if (!nameOrPath) return mdiPower
  // If it's already an SVG path string (starts with 'M' or 'm')
  if (nameOrPath.startsWith('M') || nameOrPath.startsWith('m')) {
    return nameOrPath
  }
  return iconMap[nameOrPath] || iconMap[nameOrPath.toLowerCase()] || mdiPower
}
